### PR TITLE
handle websocket endpoint

### PR DESCRIPTION
**Pull request by t4ke0**
@bi1101 please clone this PR branch (handle-websocket) and test it first then you can merge that

BTW if you see that I'm not available on Fiverr that's Okay you can message me for anything. I'm just doing that to not accept other new requests from new clients.

Thanks 👍🏿

### CODE REVIEW

**Comment by t4ke0** [comment]
@bi1101 I see that you have a conflict here just text me on Fiverr if you want help.

**Comment by bi1101** [comment]
Thanks a lot man, but I got it done on the branch Add-Gemini

**Comment by t4ke0** [comment]
> Thanks a lot man, but I got it done on the branch Add-Gemini

No problem I was just wondering if you need any help because I'm currently unavailable on Fiverr so I just want to make sure you are okay.
Thanks man 👍🏿

**Comment by t4ke0** [comment]
> @t4ke0 Hey man, I need your help re integrating Gemini, there's a few updates with Gemini that breaks compatibility

@bi1101  Hi, let me know how to help you, and I will be happy to help you with that.

I mean what to update with `Gemini`, also do you want me to close this PR? and create a new one for the new updates of `Gemini`?

**Comment by bi1101** [comment]
@t4ke0 Thanks! The idea is to integrate this as a package (so that I can easily get updates)

Like before the package should recognize models to route to the package

- Gemini-pro
- Gemini-pro-vision
The Gemini API key should be taken from the gemini-api-key.json from the root folder.

zhu327/gemini-openai-proxy: A proxy for converting the OpenAI API protocol to the Google Gemini Pro protocol. (github.com)

You can close this PR as it's fixed. Thanks

**Comment by t4ke0** [comment]
> @t4ke0 Thanks! The idea is to integrate this as a package (so that I can easily get updates)
> 
> Like before the package should recognize models to route to the package
> 
>     * Gemini-pro
> 
>     * Gemini-pro-vision
>       The Gemini API key should be taken from the gemini-api-key.json from the root folder.
> 
> 
> zhu327/gemini-openai-proxy: A proxy for converting the OpenAI API protocol to the Google Gemini Pro protocol. (github.com)
> 
> You can close this PR as it's fixed. Thanks

@bi1101 Okay allow me some time I will text you once I start on that.
Also, we can chat on Fiverr if you want I know I'm unavailable there but I still can get your messages.

Thanks 👍🏿

**Comment by bi1101** [comment]
@t4ke0 Thanks! The idea is to integrate this as a package (so that I can easily get updates)

Like before the package should recognize models to route to the package

- Gemini-pro
- Gemini-pro-vision
The Gemini API key should be taken from the gemini-api-key.json from the root folder.

zhu327/gemini-openai-proxy: A proxy for converting the OpenAI API protocol to the Google Gemini Pro protocol. (github.com)

You can close this PR as it's fixed. Thanks

Actually, I can't text you on Fiverr if you are unavailable.

**Comment by t4ke0** [comment]
> @t4ke0 Thanks! The idea is to integrate this as a package (so that I can easily get updates)
> 
> Like before the package should recognize models to route to the package
> 
>     * Gemini-pro
> 
>     * Gemini-pro-vision
>       The Gemini API key should be taken from the gemini-api-key.json from the root folder.
> 
> 
> zhu327/gemini-openai-proxy: A proxy for converting the OpenAI API protocol to the Google Gemini Pro protocol. (github.com)
> 
> You can close this PR as it's fixed. Thanks
> 
> Actually, I can't text you on Fiverr if you are unavailable.

Try from the website not phone app

**Pull request closed without merging**
